language: python
python:
  - '3.6'
  - '3.7'
dist: xenial
sudo: true
install:
  - sudo apt-get update && sudo apt-get -y install unrar
  - pip install --upgrade coverage coveralls
  - pip install -r requirements-dev.txt
script:
  - export LOCAL_TEST=$(if [ "$TRAVIS_BRANCH" != "master" ]; then echo "1"; else echo "0"; fi)
  - echo LOCAL_TEST="${LOCAL_TEST}"
  # run the majority tests without third party integration
  - coverage run -m pytest
  # run tests for `mltk.integration.pytorch` with PyTorch == 1.2.0
  - pip install torch==1.2.0
  - PYTHONPATH=$(pwd):${PYTHONPATH} coverage run -a -m pytest mltk/integration/pytorch_tests.py
  # run tests for `mltk.integration.pytorch` with PyTorch == 1.3.1
  - pip install torch==1.3.1
  - PYTHONPATH=$(pwd):${PYTHONPATH} coverage run -a -m pytest mltk/integration/pytorch_tests.py
after_success:
  - coveralls
