language: python
python:
  - '3.6'
  - '3.7'
dist: xenial
sudo: true
install:
  - sudo apt-get update && sudo apt-get -y install unrar
  - pip install -r requirements-dev.txt
script:
  - coverage run -m pytest && coveralls
