language: python
python:
  - '3.6'
  - '3.7'
dist: xenial
sudo: true
install:
  - sudo apt-get update && sudo apt-get -y install unrar
  - pip install -r requirements-dev.txt
script:
  - export LOCAL_TEST=$(if [ "$TRAVIS_BRANCH" != "master" ]; then echo "1"; else echo "0"; fi)
  - echo LOCAL_TEST="${LOCAL_TEST}"
  - coverage run -m pytest
after_success:
  - coveralls
