name: UnitTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Set up system dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install unrar
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade coverage coveralls
          pip install -r requirements-dev.txt

      - name: Test with pytest
        run: |
          export LOCAL_TEST=$(if [ "$TRAVIS_BRANCH" != "master" ]; then echo "1"; else echo "0"; fi)
          echo LOCAL_TEST="${LOCAL_TEST}"
          coverage run -m pytest

      - name: Submit coverage report to coveralls.io
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
